/* *************************
 * configuration for CKS C01
 * by wangpeng
*/
#ifndef __FPGA_CKS6Q64_H
#define __FPGA_CKS6Q64_H

#include <linux/sizes.h>

#define CONFIG_GICV3
#define GICD_BASE 0x10000000
#define GICR_BASE 0x10040000 

//ENV
#define CONFIG_ENV_SIZE 0x10000   //64KB env
#define CONFIG_SYS_MMC_ENV_DEV 0

//SYS
#define CONFIG_SYS_SRAM_BASE 0x08000000
#define CONFIG_SYS_SRAM_SIZE (SZ_2M)
#define CONFIG_SYS_SDRAM_BASE 0x40000000
#define CONFIG_SYS_SDRAM_SIZE SZ_2G
#define CONFIG_SYS_MALLOC_LEN (SZ_256K)
#define CONFIG_SYS_LOAD_ADDR CONFIG_SYS_TEXT_BASE  
#define CONFIG_SYS_INIT_SP_ADDR (CONFIG_SYS_TEXT_BASE - CONFIG_SYS_MALLOC_LEN)

#define CONFIG_SYS_MEMTEST_START CONFIG_SYS_SDRAM_BASE
#define CONFIG_SYS_MEMTEST_END (CONFIG_SYS_MEMTEST_START + SZ_1M)

#define CONFIG_SYS_HZ_CLOCK 40000000

#define CONFIG_SYS_BOOTM_LEN (SZ_64M)
#define CONFIG_SYS_MEM_RESERVE_SECURE (SZ_64M)

//SERIAL
#define CONFIG_PL011_CLOCK 40000000
#define CONFIG_PL01x_PORTS {(void *)0x1CC20000}

//G-TIMER
#define COUNTER_FREQUENCY 40000000
#define CONFIG_SYS_GTIMER_BASE 0x1B050000


//DW APB TIMER
//#define CONFIG_SYS_TIMER_BASE 0x1B040000
//#define CONFIG_SYS_TIMER_COUNTER (CONFIG_SYS_TIMER_BASE + 4)
//#define CONFIG_SYS_TIMER_CTL (CONFIG_SYS_TIMER_BASE +8)
//#define CONFIG_SYS_TIMER_COUNTS_DOWN
//#define CONFIG_SYS_TIMER_RATE 40000000

//SDMMC
#define CKS_SDMMC0_BASE 0x1C890000

//FPGA specified settings


#endif



