/* *************************
 * configuration for CKS C01
 * by zxj
*/
#ifndef __FPGA_CKS6Q32_H
#define __FPGA_CKS6Q32_H

#include <asm/arch/iomap.h>
#include <linux/sizes.h>

#define DEBUG

//ENV
#define CONFIG_ENV_SIZE 0x10000   //64KB env
//#define CONFIG_ENV_IS_NOWHERE
//#define CONFIG_SYS_MMC_ENV_DEV 0
#define CONFIG_ENV_VARS_UBOOT_RUNTIME_CONFIG

//Physical Memory Map
//#define CONFIG_NR_DRAM_BANKS    1
#define PHYS_SDRAM              DRAM_BASE_ADDR

//SYS
//#define CONFIG_SYS_SRAM_BASE 0x08000000
//#define CONFIG_SYS_SRAM_SIZE (SZ_2M)
#define CONFIG_SYS_SDRAM_BASE PHYS_SDRAM
#define CONFIG_SYS_SDRAM_SIZE SZ_2G

#define CONFIG_SYS_INIT_RAM_ADDR    IRAM_BASE_ADDR
#define CONFIG_SYS_INIT_RAM_SIZE    IRAME_SIZE

#define CONFIG_SYS_MALLOC_LEN (SZ_1M)

#define CONFIG_LOADADDR         0x12000000
#ifndef CONFIG_SYS_TEXT_BASE
#define CONFIG_SYS_TEXT_BASE    0x11000000
#endif

#define CONFIG_SYS_LOAD_ADDR    CONFIG_LOADADDR    //CONFIG_SYS_TEXT_BASE  
#define CONFIG_SYS_UBOOT_START  CONFIG_SYS_TEXT_BASE

//#define CONFIG_SYS_INIT_SP_ADDR (CONFIG_SYS_TEXT_BASE - CONFIG_SYS_MALLOC_LEN)
#define CONFIG_SYS_INIT_SP_OFFSET (CONFIG_SYS_INIT_RAM_SIZE - GENERATED_GBL_DATA_SIZE)
#define CONFIG_SYS_INIT_SP_ADDR (CONFIG_SYS_INIT_RAM_ADDR + CONFIG_SYS_INIT_SP_OFFSET)


#define CONFIG_SYS_MEMTEST_START CONFIG_SYS_SDRAM_BASE
#define CONFIG_SYS_MEMTEST_END (CONFIG_SYS_MEMTEST_START + SZ_1M)

#define CONFIG_SYS_HZ_CLOCK 50000000

#define CONFIG_SYS_BOOTM_LEN (SZ_64M)
#define CONFIG_SYS_MEM_RESERVE_SECURE (SZ_64M)


#if 0
#define CONFIG_SPL_FS_LOAD_ARGS_NAME    "args"
#define CONFIG_SPL_FS_LOAD_KERNEL_NAME    "uImage"
#define CONFIG_SYS_SPL_ARGS_ADDR    0x11800000
#define CONFIG_CMD_SPL_WRITE_SIZE   (128*SZ_1K)
#endif

#ifdef CONFIG_SPL

#define CONFIG_SPL_OS_BOOT

//#define CONFIG_SYS_THUMB_BUILD
//#define CONFIG_SPL_LDSCRIPT "arch/arm/mach-cks/cks6q32/u-boot-spl.lds"

//#define CONFIG_SPL_TEXT_BASE    0x5bb0100
#define CONFIG_SPL_STACK        0x5bc0000
#define CONFIG_SPL_MAX_SIZE     0xff00  /*0x10000-0x100*/

#define CONFIG_SPL_PAD_TO   0x10000

#define CONFIG_SPL_BSS_START_ADDR    0x10800000
#define CONFIG_SPL_BSS_MAX_SIZE      0x100000
#define CONFIG_SYS_SPL_MALLOC_START  0x10900000
#define CONFIG_SYS_SPL_MALLOC_SIZE   0x100000
#endif


//SERIAL
#define CONFIG_PL011_CLOCK 50000000
#define CONFIG_PL01x_PORTS {(void *)UART0_BASE_ADDR}

#endif



