/* *************************
 * configuration for CKS C01
 * by wangpeng
*/
#ifndef __FPGA_CKS_C01_H
#define __FPGA_CKS_C01_H

#include <linux/sizes.h>

//C01 common settings
#define CONFIG_GICV3
#define GICD_BASE 0x10000000
#define GICR_BASE 0x10080000 

//ENV
#define CONFIG_ENV_SIZE 0x10000   //64KB env
#define CONFIG_SYS_MMC_ENV_DEV 0

//SYS
#define CONFIG_SYS_SRAM_BASE 0x08000000
#define CONFIG_SYS_SRAM_SIZE (SZ_4M)
#define CONFIG_SYS_SDRAM_BASE 0x40000000
#define CONFIG_SYS_SDRAM_SIZE SZ_2G
#define CONFIG_SYS_MALLOC_LEN (SZ_256K)
#define CONFIG_SYS_LOAD_ADDR CONFIG_SYS_TEXT_BASE //last 512KB in SRAM, 0x08380000
#define CONFIG_SYS_INIT_SP_ADDR (CONFIG_SYS_TEXT_BASE - CONFIG_SYS_MALLOC_LEN)

#define CONFIG_SYS_MEMTEST_START CONFIG_SYS_SDRAM_BASE
#define CONFIG_SYS_MEMTEST_END (CONFIG_SYS_MEMTEST_START + SZ_1M)

#define CONFIG_SYS_HZ_CLOCK 40000000

#define CONFIG_SYS_BOOTM_LEN (SZ_64M)
#define CONFIG_SYS_MEM_RESERVE_SECURE (SZ_64M)

//SPL
#define CONFIG_SPL_STACK                CONFIG_SYS_INIT_SP_ADDR  //use the same stack position with u-boot
#define CONFIG_SPL_MAX_SIZE             SZ_64K	
#define CONFIG_SPL_BSS_START_ADDR       (CONFIG_SYS_LOAD_ADDR - SZ_512K)
#define CONFIG_SPL_BSS_MAX_SIZE         (SZ_512K)
#define CONFIG_SYS_MMCSD_FS_BOOT_PARTITION 1
#define CONFIG_SPL_FS_LOAD_PAYLOAD_NAME		"u-boot.img"
#define CPU_RELEASE_ADDR 0x08000000


//MMC
//MMC
#define CKS_SDMMC0_BASE 0x10100100
#define CKS_SDHC_MIN_FREQ       400000
#define CKS_SDHC_MAX_FREQ       25000000

#define CONFIG_CKS_FPGA_SDCLK 1000000

#define CKS_SDHC_GCK_RATE       240000000
#define SDHCI_TUNNING_REG               0x70


//SERIAL
#define CONFIG_PL011_CLOCK 40000000
#define CONFIG_PL01x_PORTS {(void *)0x20100000}

//G-TIMER
#define COUNTER_FREQUENCY 40000000
#define CONFIG_SYS_GTIMER_BASE 0x20300000

//DW APB TIMER
/*
#define CONFIG_SYS_TIMER_BASE 0x20200000
#define CONFIG_SYS_TIMER_COUNTER (CONFIG_SYS_TIMER_BASE + 4)
#define CONFIG_SYS_TIMER_CTL (CONFIG_SYS_TIMER_BASE +8)
#define CONFIG_SYS_TIMER_COUNTS_DOWN
#define CONFIG_SYS_TIMER_RATE 40000000
*/
//FPGA specified settings


#endif



